Feat/enhance attributes with types and tags
nmshd/cns-content pull request #14
Opened 2022-03-11 10:58 UTC by Lea-Zim

Add attributeType and tags to attribute structure and remove names.

2022-03-11 11:13 UTC, jkoenig134 commented on src/attributes/Attribute.ts
> +    public readonly metadataProperties = [nameof<Attribute>((r) => r.metadataModifiedAt)]
Es gibt keine metadata mehr, braucht man das Feld überhaupt noch?

2022-03-11 11:28 UTC, Lea-Zim commented on src/attributes/Attribute.ts
> +    public readonly metadataProperties = [nameof<Attribute>((r) => r.metadataModifiedAt)]
Eigentlich nicht, ich nehme es raus

2022-03-14 07:38 UTC, jkoenig134 requested changes

2022-03-14 07:38 UTC, jkoenig134 commented on package.json
> +    "version": "1.2.0",
wieso hat sich die Version im lockfile nicht geändert? kein `npm i` nach dem inkrementieren?

2022-03-14 07:38 UTC, jkoenig134 commented on src/attributes/Attribute.ts
>  export class Attribute extends CoreSerializable implements IAttribute {
irgendwie stört mich hier das naming. Müsste Attribute nicht AbstractAttribute extenden? Vielleicht sollten wir das hier AttributeContainer oder so nennen.

2022-03-14 07:38 UTC, jkoenig134 commented on src/attributes/index.ts
> +export * from "./types"
hier fehlt
```
export * from "./Attribute"
export * from "./AbstractAttribute"
```

2022-03-14 07:38 UTC, jkoenig134 commented on src/attributes/types/AttributeTypeMapping.ts
> +export const attributeTypeMapping = new Map<string, string[]>([
siehe `AttributeList.ts`

2022-03-14 07:38 UTC, jkoenig134 commented on src/attributes/types/AttributeList.ts
> +export const attributeList = [
da es exportiert wird würde ich das wohl eher `ATTRIBUTE_LIST` nennen

2022-03-14 07:38 UTC, jkoenig134 commented on src/attributes/types/idcard/IDCard.ts
> +export class IDCard extends AbstractAttribute {}
Wäre das nicht eher eine AbstractIDCard? Du willst ja egtl. nicht dass das jemand direkt nutzt.

2022-03-14 07:38 UTC, jkoenig134 commented on src/attributes/types/name/LegalName.ts
> +export class LegalName extends AbstractAttribute {}
Hm, wäre das nicht eher ein AbstractLegalName? Du willst ja egtl. nicht dass das jemand direkt nutzt.

2022-03-14 07:38 UTC, jkoenig134 commented on src/attributes/types/person/PersonEyeColor.ts
> +    public value: number
Sollte das nicht eher ein String sein?

2022-03-14 07:38 UTC, jkoenig134 commented on src/attributes/types/person/Sex.ts
> + * Biologisches Geschlecht
Kommentar sollte noch auf englisch sein

2022-03-14 07:38 UTC, jkoenig134 commented on src/index.ts
> +export * from "./attributes/types"
wenn du meinen Kommentar in `attributes/index.ts` umsetzt reicht hier ein export von `./attributes`

2022-03-14 07:43 UTC, tnotheis requested changes

2022-03-14 07:43 UTC, tnotheis commented on src/attributes/types/name/LegalNameDE.ts
> +    public pseudonym: Pseudonym
Optional

2022-03-14 07:43 UTC, tnotheis commented on src/attributes/types/name/LegalNameDE.ts
> +    public birthName: BirthName
Optional

2022-03-14 07:43 UTC, tnotheis commented on src/attributes/types/name/Salutation.ts
> +    public legalName?: LegalName
Wieso ist der LegalName Teil der Salutation? Ich würde sagen, es ist selten, dass man tatsächlich mit seinem kompletten legal name angesprochen wird, oder? In den meisten Fälle ist es ja entweder "Sehr geehrte(r) Herr/Frau <surname>" oder "Hallo <givenName>". Warum sollte ich der Firma dann als User den ganzen LegalName geben?

2022-03-14 07:43 UTC, tnotheis commented on src/attributes/types/person/PersonEyeColor.ts
> +    public value: number
Copy Paste Fehler beim Datentyp? Falls nicht bitte als JSDoc dazuschreiben, in welcher Codierung der Wert sein soll.

2022-03-14 07:43 UTC, tnotheis commented on src/attributes/types/person/PersonHeight.ts
> +    public value: number
Gehört zur Größe einer Person nicht auch die Einheit? Evtl. wäre auch eine Oberklasse `LengthMeasurement` (oder nur `Measurement`) gut, die dann `value` und `unit` hat, und von der `PersonHeight` erbt.

2022-03-14 07:43 UTC, tnotheis commented on test/messages/RequestMail.test.ts
> +                expect(receivedRequest.attributes[0]).to.equal("StreetAddress")
Wie kann es sein, dass dieser Test hier nicht fehlschlägt? `attributes[0]` ist doch ein Objekt. Und du vergleichst dieses Objekt mit dem String `StreetAddress`. Das kann doch eigentlich nicht gut gehen??

2022-03-14 07:43 UTC, tnotheis commented on test/messages/RequestMail.test.ts
> +                expect(receivedRequest2.attributes[1].content).to.deep.equal({ "@type": "GivenName", value: "Max" })
Spätestens hier sollte dir doch aufgefallen sein, dass etwas mit den Types nicht stimmt. ;-) `GivenName` ist in diesem Test das einzige Attribut, das eine `@type` Property hat. `street`, `houseNo`, etc. hat das nicht.

2022-03-14 07:45 UTC, jkoenig134 commented on src/attributes/Attribute.ts
> +    attributeType: string
Das feld heißt content, also eher AttributeContentType?

2022-03-14 07:46 UTC, jkoenig134 commented on src/attributes/types/AbstractDay.ts
> +export abstract class AbstractDay extends AbstractAttribute {
Da habe ich schon geschrieben, dass die abstrakt sein sollten. Die soll man ja nicht benutzen

2022-03-14 07:46 UTC, tnotheis commented on src/attributes/Attribute.ts
> +    attributeType: string
Ich glaube, das Feld sollte eher `value` heißen.

2022-03-14 07:46 UTC, jkoenig134 commented on src/attributes/types/AbstractDay.ts
> +export abstract class AbstractDay extends AbstractAttribute {
Das hier ist abstrakt, das soll nicht genutzt werden

2022-03-14 07:50 UTC, tnotheis commented on src/attributes/Attribute.ts
> +    attributeType: string
Aber ich bin nach wie vor nicht davon überzeugt, dass wir `attributeType` überhaupt brauchen. Wir duplizieren diesen Wert einzig und allein dafür, dass wir bei der Query anstatt `attribute.content.@type` `attribute.attributeType` schreiben können?

2022-03-14 07:51 UTC, jkoenig134 commented on src/attributes/Attribute.ts
> +    attributeType: string
Joa, muss eigentlich echt nicht sein.

2022-03-14 08:06 UTC, Lea-Zim commented on src/attributes/Attribute.ts
>  export class Attribute extends CoreSerializable implements IAttribute {
AttribtueContainer ist zwar sprechender, aber heißt dann das ConsumptionAttriibute auch ConsumtionAttribtueContainer?

2022-03-15 07:46 UTC, tnotheis requested changes

2022-03-15 07:46 UTC, tnotheis commented on src/attributes/types/AbstractMeasurement.ts
> +    public unit: number
Nimm besser string statt number. Das ist viel einfacher zu lesen als Entwickler. Einheiten haben ja global einheitliche Abkürzungen.

2022-03-15 07:46 UTC, tnotheis commented on src/attributes/types/person/PersonHeight.ts
> +export class PersonHeight extends AbstractMeasurement {
Ich denke, es wäre tatsächlich besser, noch eine `LengthMeasurement` Klasse dazwischen einzufügen, oder? Dann muss man nicht bei jedem Attribut, das eine Länge darstellt, die gültigen Einheiten definieren.

Wobei das auch fragwürdig ist. Will man wirklich, dass die Größe einer Person in pm angegeben wird? ;-) 

Andererseits wiederum: wieso nicht?

2022-03-15 07:46 UTC, tnotheis commented on src/attributes/types/person/PersonHeight.ts
> +    @validate({ customValidator: (v) => (!LengthUnit[v] ? "has invalid value" : undefined) })
Nachdem du die `unit` zu einem String gemacht hast, ändere bitte auch die Fehlermeldung auf folgendes ab: 
```
@validate({ customValidator: (v) => (!LengthUnit[v] ? `must be one of: ${Object.keys(LengthUnit)}` : undefined) })
```
Falls du es bei number belassen willst, müssen wir das Object.keys nochmal filtern, weil sonst zu viel ausgegeben wird.

2022-03-15 07:50 UTC, jkoenig134 requested changes

2022-03-15 07:50 UTC, jkoenig134 commented on src/attributes/AbstractAttributeValue.ts
> +@type("AbstractAttribute")
Das muss entweder weg (weil abstrakt) oder `@type("AbstractAttributeValue")` heißen

2022-03-15 07:50 UTC, jkoenig134 commented on src/attributes/types/AbstractMeasurement.ts
> +/**
Die tsdocs sind irgendwie immer anders formatiert, mach die bitte immer direkt an das Objekt, das sie dokumentieren.

2022-03-15 07:50 UTC, jkoenig134 commented on src/attributes/types/AbstractMonth.ts
> +/**
Siehe `src/attributes/types/AbstractMeasurement.ts`

2022-03-15 08:16 UTC, stnmtz commented on src/attributes/types/person/PersonHeight.ts
> +export class PersonHeight extends AbstractMeasurement {
Ich finde die Idee mit dem LengthMeasurement gut - ist halt nur die Frage, ob wir das gerade Over-Engineeren. Es macht das Handling der Attribute aber wohl um Längen "normierter" - ha, Karlauer! ;)

2022-03-15 11:22 UTC, jkoenig134 requested changes

2022-03-15 11:22 UTC, jkoenig134 commented on src/attributes/Attribute.ts
> +import { ContentJSON } from "@nmshd/content"
in content sollte man nicht von content importieren.

2022-03-15 11:22 UTC, jkoenig134 commented on src/attributes/types/person/PersonHeight.ts
> +enum LengthUnit {
wenn du hier die LengthUnit weiter einschränkst würde ich eher sagen dass man unten `public unit: LengthUnit = LengthUnit.CM` benutzt (die LengthUnit die schon vordefiniert sind), oder halt ein PersonHeightUnit enum machen statt LengthUnit

2022-03-15 11:53 UTC, tnotheis commented on src/attributes/types/address/HouseNo.ts
> +export class HouseNo extends AbstractAttributeValue {
Sollten wir das nicht eher HouseNumber nennen? ;) Wir haben sonst ja auch keine Abkürzungen in den Klassennamen.

2022-03-15 11:53 UTC, tnotheis commented on src/attributes/types/person/PersonHeight.ts
> +enum LengthUnit {
> würde ich eher sagen dass man unten `public unit: LengthUnit = LengthUnit.CM` benutzt

Das ergibt keinen Sinn. Damit wäre ja der Default Value CM. Meinst du `public unit: LengthUnit.CM`?

2022-03-15 11:53 UTC, tnotheis commented on src/attributes/Attribute.ts
> +import { ContentJSON } from "@nmshd/content"
Hmm, ich werd das mit den Imports bei den Tests nie verstehen. Manchmal muss man es so importieren, und das andere mal darf man es nicht so importieren

2022-03-15 11:54 UTC, Lea-Zim commented on src/attributes/types/person/PersonHeight.ts
> +enum LengthUnit {
Beides ist etwas schwieriger...beim = LengthUnit.CM muss trotzdem beim Erstellen unit gesetzt werden und wird dann überschrieben. Bei einem neuen Enum meckert TS, weil es nicht der gleiche Typ ist. Würde das aktuell so lassen

2022-03-15 11:56 UTC, jkoenig134 commented on src/attributes/types/person/PersonHeight.ts
> +enum LengthUnit {
Es sollte kein Problem sein die LengthUnit hier PersonHeightLengthUnit zu nennen. Du mussts eh exportieren.

Oder wie wäre es mit `public unit: LengthUnit.CM | LengthUnit.M`

2022-03-15 11:56 UTC, jkoenig134 commented on src/attributes/Attribute.ts
> +import { ContentJSON } from "@nmshd/content"
Das ist nicht in tests

2022-03-15 11:57 UTC, Lea-Zim commented on src/attributes/Attribute.ts
> +import { ContentJSON } from "@nmshd/content"
Bei den Tests wird es ersetzt durch: 
"paths": {
            "@nmshd/content": ["../dist"]
        }
soweit ich das verstanden habe, oder?

2022-03-15 12:00 UTC, jkoenig134 commented on src/attributes/Attribute.ts
> +import { ContentJSON } from "@nmshd/content"
Damit verstehen typescript in VSCode + die node tests das. In den Webtests macht das webpack.

2022-03-15 12:03 UTC, tnotheis commented on src/attributes/types/person/PersonHeight.ts
> +enum LengthUnit {
Ich weiß nicht ob ts-serval damit klarkommt. Das hat so ein wenig seine Schwierigkeiten mit Unions. Von daher würde ich sagen wir mergen jetzt erstmal. Aktuell wäre es nur ein Usability-Problem (weil der Fehler zur Laufzeit anstatt zur Compile-Zeit kommt). Und das kann man ja später noch optimieren.

2022-03-15 12:07 UTC, tnotheis approved these changes

2022-03-15 12:24 UTC, jkoenig134 commented on src/attributes/types/person/PersonHeight.ts
> +enum LengthUnit {
IMO ist das nicht resolved: LengthUnit muss exportiert werden und damit zu PersonHeightLengthUnit umbenannt werden, sost ist PersonHeight nicht benutzbar.

2022-03-15 14:53 UTC, tnotheis approved these changes

2022-03-15 14:54 UTC, jkoenig134 approved these changes

2022-03-15 14:56 UTC, merged