Feature/add xml attributes
nmshd/cns-content pull request #144
Opened 2023-07-24 11:40 UTC by vinzlange

Add AbstractXML and StandardizedXML

2023-07-24 11:57 UTC, jkoenig134 commented on test/attributeValues/StandardizedXML.test.ts
> +import { StandardizedXML } from "../../src/attributes/types/proprietary/StandardizedXML"
you have to import from "@js-soft/ts-serval" here. this will fix the test problems

2023-07-24 11:59 UTC, jkoenig134 commented on test/attributeValues/StandardizedXML.test.ts
> +            "test/attributeValues/hochschulabschlusszeugnis.xml",
this is not allowed in the web context (browsertests), you have to put this in a ts file as string

2023-07-24 12:00 UTC, jkoenig134 commented
missing version bump + you should also bump ts-serval to test Thomas' changes

2023-07-24 12:03 UTC, vinzlange commented on test/attributeValues/StandardizedXML.test.ts
> +import { StandardizedXML } from "../../src/attributes/types/proprietary/StandardizedXML"
you meant from "@nmshd/content" ?

2023-07-24 12:04 UTC, jkoenig134 commented on test/attributeValues/StandardizedXML.test.ts
> +import { StandardizedXML } from "../../src/attributes/types/proprietary/StandardizedXML"
yep

2023-07-24 13:58 UTC, jkoenig134 approved these changes

2023-07-24 14:24 UTC, jkoenig134 approved these changes

2023-07-25 08:04 UTC, jkoenig134 approved these changes

2023-07-25 08:20 UTC, jkoenig134 requested changes

2023-07-25 08:20 UTC, jkoenig134 commented on package.json
missing version bump again. I suggest using 2.4.0

2023-07-25 08:25 UTC, jkoenig134 approved these changes

2023-07-25 08:34 UTC, merged