Refactor/file reference
nmshd/cns-content pull request #145
Opened 2023-08-02 20:39 UTC by kojofl

Update FileReference to IdentityFileReference to avoid naming conflicts with the transport library in the enmeshed runtime.

2023-08-02 20:42 UTC, jkoenig134 requested changes

2023-08-02 20:42 UTC, jkoenig134 commented on src/attributes/hints/RenderHintsDataType.ts
> +    IdentityFileReference = "IdentityFileReference",
I think here it should stay FileReference

2023-08-02 20:57 UTC, jkoenig134 submitted a review, later dismissed

2023-08-03 05:06 UTC, tnotheis requested changes

2023-08-03 05:06 UTC, tnotheis commented on src/attributes/types/identity/IdentityFileReference.ts
> +    "@type": "FileReference"
Hier hast du was vergessen

2023-08-03 05:09 UTC, tnotheis commented on src/attributes/types/identity/IdentityFileReference.ts
> +@type("FileReference")
Und hier natürlich auch. Das Wichtigste

2023-08-03 06:42 UTC, tnotheis approved these changes

2023-08-03 06:47 UTC, merged

2023-08-03 06:47 UTC, jkoenig134 approved these changes