Feature/jssnmshdd 2851 new requests
nmshd/cns-content pull request #15
Opened 2022-03-16 07:45 UTC by tnotheis

2022-03-16 07:48 UTC, tnotheis commented on test/tsconfig.json
> +        "target": "es2021",
Ach ja, das hab ich mal reingemacht, um was auszuprobieren.

Das gibt aber wahrscheinlich Probleme, weil alle folgenden Libraries dann auch auf mind. es2021 gehen müssen, oder?

2022-03-16 12:03 UTC, jkoenig134 commented on src/requests/v2/RequestV2.ts
> +export class RequestItemV2 extends SerializableAsync {
Sollte das nicht alles in eigene Dateien? Dann kannst du `**********************************************Classes*********************************************************` auch weg machen

2022-03-16 12:04 UTC, jkoenig134 commented on src/requests/v2/Response.ts
> +export enum ResponseItemStatus {
auch eigene Dateien?

2022-03-16 12:04 UTC, jkoenig134 commented on test/tsconfig.json
> +        "target": "es2021",
sollte man vllt auch in Runtime, AppRuntime, ... anpassen.

2022-03-16 12:05 UTC, jkoenig134 submitted a review, later dismissed

2022-03-16 12:20 UTC, tnotheis commented on src/requests/v2/RequestV2.ts
> +export class RequestItemV2 extends SerializableAsync {
Ich hatte mich an die bisherige Struktur gehalten. Aber vielleicht hast du recht. Ich fand das auch schon sehr unübersichtlich. Ich lagere es mal aus.

2022-03-17 07:04 UTC, jkoenig134 requested changes

2022-03-17 07:04 UTC, jkoenig134 commented on src/requests/v2/RequestV2.ts
> +    key?: string
Wenn der key in der neuen Datenstruktur direkt deprecated ist, kann er nicht einfach weg? Oder hab ich was vergessen?

2022-03-17 07:04 UTC, jkoenig134 commented on src/requests/v2/ResponseItem.ts
> +export class ResponseItemAcceptContent extends SerializableAsync {}
Ist die nicht eigentlich abstrakt?

2022-03-17 12:58 UTC, jkoenig134 commented on src/requests/RequestItem.ts
> +    @serialize()
hier fehlt ne Leerzeile 🤣

2022-03-17 12:59 UTC, jkoenig134 commented on src/requests/ResponseItem.ts
> +@type("ResponseItemAcceptContent")
type muss weg (abstract)

2022-03-17 16:11 UTC, tnotheis commented
So, sollte jetzt alles passen. Ich hab übrigens bewusst AttributesChangeRequest und AttributesShareRequest noch nicht als deprecated markiert, weil wir ja aktuell noch keinen Ersatz haben.

2022-03-17 19:40 UTC, jkoenig134 approved these changes

2022-03-18 06:14 UTC, merged