extend IQLQuery with creation hints as a fallback mechanism
nmshd/cns-content pull request #154
Opened 2023-09-21 14:47 UTC by slavistan

2023-09-21 14:57 UTC, jkoenig134 requested changes

2023-09-21 14:57 UTC, jkoenig134 commented on src/attributes/IQLQuery.ts
> +    public creationHints?: {
Has to be a class (See relationship Attribute creation hints)

2023-09-22 06:07 UTC, slavistan commented on src/attributes/IQLQuery.ts
> +    public creationHints?: {
Alright, will change. What's the reason that this needs to be a class?

2023-09-22 06:15 UTC, jkoenig134 commented on src/attributes/IQLQuery.ts
> +    public creationHints?: {
- safe serialization and validation
- I don't know if serval can handle inline definitions at all
- look at the rest of the codebase

2023-09-22 07:12 UTC, jkoenig134 requested changes

2023-09-22 07:12 UTC, jkoenig134 commented on src/attributes/IQLQuery.ts
> +    }
```suggestion
    creationHints?: IQLQueryCreationHintsJSON
```

2023-09-22 07:12 UTC, jkoenig134 commented on src/attributes/IQLQuery.ts
> +    }
```suggestion
    creationHints?: IIQLQueryCreationHints
```

2023-09-22 07:55 UTC, jkoenig134 approved these changes

2023-09-22 07:55 UTC, merged

2023-09-22 07:57 UTC, stnmtz approved these changes