Feature/jssnmshdd 2926 allow handling of deprecated attributes
nmshd/cns-content pull request #35
Opened 2022-04-04 08:37 UTC by Lea-Zim

2022-04-04 10:22 UTC, tnotheis requested changes
Also ich würde sagen, dass 
1. `content` nicht optional sein sollte
2. `name` und `value` nicht Teil von `IAttribute`/`Attribute'  sein sollten.

Grund: als Entwickler muss man nicht wissen, dass es die alte Variante der Attribute gibt. Die alten Attribute kommen nur in alten Daten vor. Alle neuen **müssen** direkt die `content` Property gesetzt haben. Und wenn ein Attribut in alten Daten vorkommt, dann wird die from-Methode auch generisch aufgerufen, d.h. da beschwert sich auch TypeScript nicht.

Einzig und alleine im Test wird sich TypeScript beschweren, und da kann man ja mit einem Cast auf any arbeiten.

2022-04-04 10:22 UTC, tnotheis commented on test/attributes/Attribute.test.ts
> +                    validFrom: { date: DateTime.utc().minus({ years: 1 }).toString() },
Wieso diese Änderung?

2022-04-04 11:55 UTC, tnotheis commented on test/attributes/Attribute.test.ts
> +                    validFrom: { date: DateTime.utc().minus({ years: 1 }).toString() },
Ach ja, hab' gerade gesehen warum du es jetzt machst. Aber wieso war das vorher kein Problem?? 

Wie auch immer: ich würde eher 

```ts
validFrom: CoreDate.utc().subtract({ years: 1 })
```

schreiben.

2022-04-05 14:11 UTC, tnotheis requested changes

2022-04-05 14:11 UTC, tnotheis commented on src/relationships/RelationshipTemplateBody.ts
> +import { AttributeV2, AttributeV2JSON, IAttributeV2 } from "../attributes/AttributeV2"
@stnmtz Sollte RelationshipTemplateBody nicht gelöscht werden? Wir wollten ja alle Altlasten loswerden, und RelationshipTemplatBody ist so eine Altlast, oder?
Aber falls wir es erstmal noch behalten wollen, sollte es zumindest weiterhin AttributeV1 benutzen(?)

2022-04-05 14:11 UTC, tnotheis commented on src/requests/old/AttributesChangeRequest.ts
> +    attributes: AttributeV2JSON[]
Hier sollte noch AttributeV1 benutzt werden. Sonst können vorhandene AttributesChangeRequests nicht deserialisiert werden.

2022-04-05 14:11 UTC, tnotheis commented on src/requests/old/AttributesChangeRequest.ts
> -    public static async fromJSON(value: AttributesChangeRequestJSON): Promise<AttributesChangeRequest> {
Warum hast du diese Methode gelöscht?

2022-04-05 14:11 UTC, tnotheis commented on test/attributes/Attribute.test.ts
> +    AttributeV2,
Ich würde sagen, du solltest die Tests für das AttributeV1 nicht abändern. Stattdessen eine Kopie davon unter dem Namen "AttributeV2.test.ts" anlegen, und darin deine Änderungen machen. 

Sonst ist ja AttributeV1 nicht mehr getestet.

2022-04-06 07:55 UTC, stnmtz requested changes

2022-04-06 07:55 UTC, stnmtz commented on src/attributes/types/AbstractMonth.ts
> +    @validate({ customValidator: (v) => (!Month[v] || !Number.isInteger(v) ? "has invalid value" : undefined) })
@validate({min: 1, max:12})?

2022-04-06 07:55 UTC, stnmtz commented on src/attributes/types/idcard/IDCardIssuingDate.ts
> +    public day: IssuingDay
Hier kam ja raus, dass wir keine speziellen IssuingDay/Month/Year benötigen.

2022-04-06 07:55 UTC, stnmtz commented on src/relationships/RelationshipCreationChangeRequestBody.ts
>  export interface RelationshipCreationChangeRequestBodyJSON extends ContentJSON {
ich glaube der gesamte relationships folder kann gelöscht werden

2022-04-06 07:55 UTC, stnmtz commented on src/relationships/RelationshipTemplateBody.ts
> +import { AttributeV2, AttributeV2JSON, IAttributeV2 } from "../attributes/AttributeV2"
siehe oben, auch request

2022-04-06 07:55 UTC, stnmtz commented on src/requests/old/AttributesChangeRequest.ts
> +    attributes: AttributeV2JSON[]
Ja

2022-04-06 07:55 UTC, stnmtz commented on src/requests/old/AttributesChangeRequest.ts
> +    @serialize({ type: AttributeV2 })
Überall Attribute lassen, das ist eine alte Klasse

2022-04-06 07:55 UTC, stnmtz commented on test/attributes/Attribute.test.ts
> +    AttributeV2,
Ja

2022-04-06 07:55 UTC, stnmtz commented on test/attributes/Attribute.test.ts
> +                    expect(birthDate.value.day).to.be.instanceOf(BirthDay)
wenn ich das so lese, finde ich value hier definitiv besser als content ;) Gute Entscheidung

2022-04-06 07:58 UTC, tnotheis commented on src/attributes/types/AbstractMonth.ts
> +    @validate({ customValidator: (v) => (!Month[v] || !Number.isInteger(v) ? "has invalid value" : undefined) })
Geht nicht. Es muss ja noch geprüft werden, ob es ein Integerwert ist. D.h. man brauht einen customValidator. Und dann werden min und max nicht gechecked. Zumindest hab ich das gestern kurz bei mir ausprobiert, und es hatte nicht funktioniert.

2022-04-06 08:30 UTC, tnotheis commented on src/attributes/Attribute.ts
>  export interface IAttribute extends ICoreSerializable {
Hä? Wieso müssten wir alles auf V2 suffixen? Es hat sich doch nur die Version des Attributs geändert. Alle anderen Typen bleiben gleich, also gibt es auch keinen Grund, deren Versionen zu ändern.

Aber wir können von mir aus auch Attribute lassen. Dachte nur wir hätten es anders besprochen.

2022-04-07 13:05 UTC, tnotheis requested changes

2022-04-07 13:05 UTC, tnotheis commented on src/attributes/types/person/Sex.ts
> +export class Sex extends AbstractStringValue {}
Wäre hier nicht ein Enum mit den Werten male, female (und both? keine Ahnung was hier die wissenschaftlich korrekte Definition ist) besser?

2022-04-07 13:06 UTC, tnotheis commented
Sorry, da sind 2-3 neue Anmerkungen dazugekommen, die ich vorher noch nicht bemerkt habe.

2022-04-07 14:35 UTC, stnmtz commented on src/attributes/types/AbstractDay.ts
> +export abstract class AbstractDay extends AbstractIntegerValue {
Ich wollte gerade sagen, dass das nicht geht. Aber ich glaube tatsächlich, dass du recht hast. Wenn jemand ein eigenes Property anlegen müsste, haben wir den Salat schon. Da wird ja auf genau diese abstrakten Attribute zugegriffen und das mit einem speziellen Tag erstellt.

2022-04-07 15:01 UTC, Lea-Zim commented on src/attributes/types/AbstractDay.ts
> +export abstract class AbstractDay extends AbstractIntegerValue {
Wir können gerne noch zb CustomString, CustomInteger etc anlegen. Das würde ich gerne machen, wenn wir absehen können, wofür wir die Typen brauchen

2022-04-07 15:15 UTC, stnmtz submitted a review, later dismissed

2022-04-08 05:58 UTC, tnotheis commented on src/attributes/AttributeV2.ts
> +    public static from(attribute: IAttributeV2): AttributeV2 {
Könnte aber potentiell verwendet werden. Ich würde es auf jeden Fall mal anbieten.

2022-04-08 06:07 UTC, tnotheis commented on src/attributes/types/AbstractDay.ts
> +export abstract class AbstractDay extends AbstractIntegerValue {
Ich verstehe nicht ganz, wieso wir dafür eigene Ableitungen brauchen sollten. Ich hätte einfach nur gesagt, dass es anstatt eines `AbstractDay` einen `Day` gibt. Aber du hast trotzdem recht: wir können damit auch noch warten. Wir verbauen uns ja nichts damit, wenn das erstmal abstrakt bleibt.

2022-04-08 06:37 UTC, Lea-Zim commented on src/attributes/AttributeV2.ts
> +    public static from(attribute: IAttributeV2): AttributeV2 {
Vermutlich übersehen: die Conversation ist outdated, das habe ich gestern angepasst. Resolve nochmal ;)

2022-04-08 06:39 UTC, Lea-Zim commented on src/attributes/types/AbstractDay.ts
> +export abstract class AbstractDay extends AbstractIntegerValue {
Steht oben: weil es erst einmal wenig Sinn ergibt, einen einzelnen Day ohne weitere Info zu speichern, schicken oder anzufordern. Wenn wir Tagging fertig haben, kann man noch Infos zufügen und dann gerne auch die Custom Datentypen. Aber aktuell wäre eine Anfrage dann: gib mir bitte einen Tag.

2022-04-08 07:05 UTC, tnotheis approved these changes

2022-04-08 07:07 UTC, merged