Feature/jssnmshdd 2931 attribute preparation v2
nmshd/cns-content pull request #38
Opened 2022-04-25 16:39 UTC by stnmtz

2022-04-26 08:19 UTC, Lea-Zim commented on src/attributes/types/proprietary/ProprietaryHEXColor.ts
> +@type("ProprietaryHEXColor")
hier auch wieder: wann heißt es value, wann nicht?

2022-04-26 08:19 UTC, Lea-Zim commented on src/attributes/types/strings/AbstractDataURLValue.ts
> +    public override value: string
wird value nicht implizit überschrieben, auch ohne override?

2022-04-26 08:19 UTC, Lea-Zim commented on src/attributes/types/strings/AbstractPhoneNumberValue.ts
> +    public override value: string
Ich verstehe noch nicht ganz den Sinn hinter den ganzen Abstract*Values. Wenn wir dafür validator einführen, dann aj, ansonsten erben sie alle von AbstractStringValue etc, aber fügen keine weitere Logik oder Bedeutung ein und müssen dann sowieso ausimplementiert werden. Dann lieber nur die Standard-Datentypen und alles, was nochmal eigene Logik hinzufügt

2022-04-26 09:35 UTC, tnotheis commented on src/attributes/types/strings/AbstractDataURLValue.ts
> +    public override value: string
override ist nur eine Möglichkeit von TypeScript zu verdeutlichen, dass an dieser Stelle ein override Stattfindet. Wir haben es vor kurzem zur Pflicht gemacht, dass man override angeben muss. Das hat (mind.) 2 Vorteile: zum einen beschwert sich der Compiler, wenn du **ausversehen** etwas überschreibst. Und zum anderen sieht man direkt, **dass** eine Property/Methode eine andere überschreibt.

2022-04-26 09:38 UTC, tnotheis commented on src/attributes/types/strings/AbstractPhoneNumberValue.ts
> +    public override value: string
Also ein Grund für die abstrakten Typen ist, dass man daraus manche Rendering-Informationen ableiten kann (z.B. dass ein Date Picker verwendet werden soll, wenn nach einem Attribut gefragt wird, das von AbstractDateStringValue erbt)

2022-04-26 10:48 UTC, stnmtz commented on src/attributes/AbstractAttributeQuery.ts
> +    validityPeriod?: IAbstractPeriod
Die RelationshipAttributeQuery hat und auch den Owner, damit ich hier unterscheiden kann, auf welchen Datensatz der Relationship ich schreibe. Bei der IdentityAttributeQuery brauche ich keinen Owner, es handelt sich immer um den "Peer". Ich kann ja nur unbekannte Attribute abfragen und die von mir selbst kenn ich ja schon.

2022-04-27 08:37 UTC, stnmtz commented on src/attributes/IdentityAttribute.ts
> +    public readonly store: "Identity" = "Identity"
Eigentlich nein, wir hatten uns dafür entschieden das über eine zusätzliche Property zu lösen, da wir ansonten in den DB-Queries auf die "@type" Properties zugreifen müssten. Das wird dann höllisch komplex, wenn wir da irgendwann noch ne Vererbung hätten.

2022-04-27 08:37 UTC, stnmtz commented on src/attributes/AbstractAttributeQuery.ts
> +    public validityPeriod?: AbstractPeriodValue
Gute Frage... ich versuche das ins Confluence zu schreiben.

2022-04-27 08:38 UTC, stnmtz commented on src/attributes/IdentityAttribute.ts
> +}
Theoretisch bräuchten wir dafür die "IdentityVersionNumber", die eine "IdentityV2" auf die entsprechenden Klassen mappt. Ist out of scope.

2022-04-27 08:39 UTC, stnmtz commented on src/attributes/RelationshipAttributeQuery.ts
> +    owner: string
Siehe oben, dann brauchst du nicht queryen, du kennst die Infos schon und machst ne DB-Query auf Consumption Attributes.

2022-04-27 08:41 UTC, stnmtz commented on src/attributes/types/address/AbstractAddress.ts
> +    recipient: string
Das ist doch schon die ganze Zeit required? Insofern gehört die Frage eigentlich nicht in den PR ;)
Andererseits: Du brauchst bei einer Anschrift eigentlich IMMER einen Namen, auch bei einer DeliveryBoxAddress. Das wird halt eigentlich dann automatisch gesetzt. Ich denke schon, dass wir das Required setzen sollten?

2022-04-28 12:09 UTC, stnmtz commented on src/attributes/IdentityAttribute.ts
> +    public readonly store: "Identity" = "Identity"
@tnotheis kannst du hier noch mal was zu sagen? Lea meint gerade, dass wir bei den Values das "@ type" schon querien, warum es dann hier unterschiedlich ist, ist halt die Frage ;)

2022-04-28 12:15 UTC, tnotheis commented on src/attributes/IdentityAttribute.ts
> +    public readonly store: "Identity" = "Identity"
Also ich hab kein Problem damit, auf @type zu querien. 

Ich schätze, dass der `store` hier nur Altlast ist. Zeitweise gab es ja keine `IdentityAttribute` und `RelationshipAttribute` Klassen.

2022-04-28 15:05 UTC, tnotheis commented on src/attributes/IdentityAttribute.ts
> +    public readonly store: "Identity" = "Identity"
> Ah, also Altlast von der initialen Idee die beiden zu trennen aber ohne verschiedene Typen?
Genau

> Dann würde ich das tatsächlich rausnehmen
Ja, würde ich auch sagen

2022-04-29 11:20 UTC, tnotheis requested changes

2022-04-29 11:20 UTC, tnotheis commented on src/attributes/types/person/Picture.ts
> +export class Picture extends AbstractDataURL {}
Kann es keine FileReference sein?

2022-04-29 11:20 UTC, tnotheis commented on src/attributes/types/person/Sex.ts
> +    public override value: BiolSex
Warum diese merkwürdige Abkürzung ("Biol")?

2022-04-29 11:20 UTC, tnotheis commented on src/attributes/types/strings/AbstractDataURL.ts
> +    public override value: string
Warum dieser override?

2022-04-29 11:20 UTC, tnotheis commented on src/attributes/types/strings/AbstractDataURL.ts
> +export abstract class AbstractDataURL extends AbstractString {
Sollte `AbstractDataURL` nicht von `AbstractURL` erben?

2022-04-29 11:20 UTC, tnotheis commented on src/attributes/types/strings/AbstractURL.ts
> +export abstract class AbstractURL extends AbstractString {
Validierung über einen RegEx?

2022-04-29 11:20 UTC, tnotheis commented on src/attributes/types/strings/AbstractHEXColor.ts
> +    @validate({ regExp: new RegExp("^#([0-9A-F]{3}){1,2}$", "i") })
Ich hätte gesagt, dass wir ruhig auch Kleinbuchstaben zulassen können. Es gibt meines Erachtens keinen Grund dafür, das einzuschränken.

2022-04-29 11:20 UTC, tnotheis commented on src/attributes/types/strings/AbstractPhoneNumber.ts
> +    public override value: string
Wieder unnötiger Override?

2022-04-29 11:20 UTC, tnotheis commented on src/attributes/types/strings/AbstractURL.ts
> +    public override value: string
Unnötiger Override?

2022-04-29 11:20 UTC, Lea-Zim submitted a review, later dismissed

2022-04-29 12:19 UTC, stnmtz commented on src/attributes/IdentityAttribute.ts
> +        T extends AbstractAttributeValue = AbstractAttributeValue,
Hmmm, ok. Ich habe es mal `TValueClass`, `TValueInterface` und `TValueJSONInterface` genannt.

2022-04-29 12:23 UTC, stnmtz commented on src/attributes/types/strings/AbstractDataURL.ts
> +export abstract class AbstractDataURL extends AbstractString {
:D Also vorher war es DataURI und URL. DataURI ist deprecated, insofern DataURL.

Aber eine URL ist für mich eine Internet-Adresse und keine URN oder ein Datensatz wie eine DataURL. Eine URL kann man meines Erachtens immer im Browser öffnen und es tut sich was.

Was genau machen wir jetzt? Das sind schon zwei verschiedene Dinge, die wir auch ggf. anders benutzen sollten (z.B. Browser Öffnen vs. Bild anzeigen).

2022-04-29 12:23 UTC, stnmtz commented on src/attributes/types/strings/AbstractHEXColor.ts
> +    @validate({ regExp: new RegExp("^#([0-9A-F]{3}){1,2}$", "i") })
Got ya :P Das case-insensitive Flag ist gesetzt ;)

2022-04-29 15:21 UTC, Lea-Zim commented on src/attributes/IdentityAttribute.ts
> +}
Zuerst war es K, T, T und in der from Methode K, T, I. Mein Kommentar war, dass die Typen einheitlich zur from Methode benannt werden sollen und das hat Thomas gemacht

2022-04-29 19:04 UTC, stnmtz commented on src/attributes/types/dates/AbstractPeriod.ts
> +    public static from(value: IAbstractPeriod | AbstractPeriodJSON): AbstractPeriod {
Humm, ich merke gerade, dass wir das mit Serval eigentlich relativ schlecht abbilden können.

2022-05-02 05:21 UTC, tnotheis commented on src/attributes/types/dates/AbstractPeriod.ts
> +    public static from(value: IAbstractPeriod | AbstractPeriodJSON): AbstractPeriod {
Und jetzt? Erstmal so lassen und nach der Shit-in-Shit-out-Methode verfahren? :)

2022-05-02 05:41 UTC, tnotheis commented on src/attributes/types/name/LegalNameDE.ts
> +    givenNames?: GivenName[] | IAbstractString[] | string[]
@stnmtz Als wir am Freitag telefoniert hatten, hast du doch, wenn ich mich richtig erinnere, überlegt, ob givenNames nicht Pflicht sein sollte. Hat sich das erledigt?

2022-05-02 05:41 UTC, tnotheis commented on src/attributes/types/measurements/AbstractMeasurement.ts
> +        return `${this.value}${this.unit}`
Ich glaube, dass man normalerweise zwischen zwischen Zahl und Einheit ein Leerzeichen schreibt (s. https://www.scribbr.de/wissenschaftliches-schreiben/leerzeichen/)

2022-05-02 05:41 UTC, tnotheis commented on src/attributes/types/strings/AbstractPhoneNumber.ts
> +    @validate({ regExp: new RegExp(/^[\d+\-x#*() ]{3,100}$/) })
Ich hab gerade mal gegoogelt, welche Zeichen in einer Telefonnummer erlaubt sind. Leider findet man kaum etwas dazu. Das, was dem am nächsten kommt, war, eine Frage in einem Microsoftforum, in der eine Fehlermeldung von Microsoft zitiert wird: 

> The phone number you entered isn't valid. Your phone number can contain numbers, spaces, and these special characters: ( ) [ ] . - * /

Demnach fehlen bei uns noch die eckigen Klammern und natürlich auch der `/`.

2022-05-02 10:46 UTC, tnotheis approved these changes

2022-05-02 11:11 UTC, merged